### ISSUE TITLE
AttributeError: module 'dizqueTV.decorators' has no attribute '_make_program_dict_from_plex_item'

### ISSUE THREAD

**Issue by morlanth** [nwithan8/dizqueTV-scripts#4]
When running the scripts I'm receiving this error:

```
$:media@plex>pseudotv>/o/p/scripts:: python playlist_to_channel.py "Movies: Recently Released" -c 10

Traceback (most recent call last):
  File "playlist_to_channel.py", line 66, in <module>
    item = dtv.convert_plex_item_to_program(plex_item=item,
  File "/etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages/dizqueTV/dizquetv.py", line 1003, in convert_plex_item_to_program
    return convert_plex_item_to_program(plex_item=plex_item, plex_server=plex_server)
  File "/etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages/dizqueTV/dizquetv.py", line 70, in convert_plex_item_to_program
    data = decorators._make_program_dict_from_plex_item(plex_item=plex_item, plex_server=plex_server)
AttributeError: module 'dizqueTV.decorators' has no attribute '_make_program_dict_from_plex_item'
```

I have installed the Python dependencies:

```
Requirement already satisfied: plexapi in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (4.1.0)
Requirement already satisfied: dizqueTV in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.2.3.0)
Requirement already satisfied: m3u8 in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from dizqueTV->-r requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: requests in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from dizqueTV->-r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: iso8601 in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from m3u8->dizqueTV->-r requirements.txt (line 2)) (0.1.13)
Requirement already satisfied: idna<3,>=2.5 in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from requests->dizqueTV->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from requests->dizqueTV->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from requests->dizqueTV->-r requirements.txt (line 2)) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /etc/miniconda3/envs/pseudotv/lib/python3.8/site-packages (from requests->dizqueTV->-r requirements.txt (line 2)) (4.0.0)
```
Running dizqueTV 1.2.3

**Comment by nwithan8** [comment]
I was afraid of that. I had done a rename on a file, and I thought I replaced all instances of it, but apparently not. Thanks for letting me know.
1.2.3.1 will be out shortly to patch it.

**Comment by nwithan8** [comment]
Patch has been released.
Update to the latest version with ``pip install --upgrade dizquetv``
